--liquibase formatted sql
--changeset slair:2025_01_20-01-acct-create_account_table

CREATE TABLE account (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) UNIQUE NOT NULL,
    encoded_password BYTEA NOT NULL,
    email VARCHAR(52) UNIQUE NOT NULL,
    is_locked BOOLEAN NOT NULL DEFAULT false,
    is_disabled BOOLEAN NOT NULL DEFAULT false,
    are_credentials_expired BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email_verified_at TIMESTAMP NOT NULL DEFAULT TIMESTAMP 'epoch',
    logged_out_at TIMESTAMP NOT NULL DEFAULT TIMESTAMP 'epoch'
);
