--liquibase formatted sql
--changeset slair:2025_01_20-01-cms-create_profile_table

CREATE TABLE profile (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER UNIQUE NOT NULL REFERENCES account(id),
    display_name VARCHAR(20) UNIQUE NOT NULL,
    bio TEXT,
    is_banned BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
