--liquibase formatted sql
--changeset slair:2025_01_25-01-cms-create_direct_message_table

CREATE TABLE direct_message (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INTEGER REFERENCES profile(id),
    recipient_id INTEGER REFERENCES profile(id),
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited_at TIMESTAMP NOT NULL DEFAULT TIMESTAMP 'epoch',
    read_at TIMESTAMP NOT NULL DEFAULT TIMESTAMP 'epoch'
);
